node_type_light_status: '0'
node_type_light_pattern: '[node:field_action]'
node_type_light_php: 0
submit: 'Save configuration'
form_build_id: form-Yt2bi6_fbQnu5QJitmiMgISRyf55VjsEWzmBW3RHO7M
form_token: NCdF7psBRCi_QXJFxUOuxiYSNay5zZgFlHcyNSLJGrA
form_id: auto_entitylabel_settings_form
op: 'Save configuration'
