definitions:
  contact__site_page:
    weight: -42
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  user__page:
    weight: -49
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  user__logout:
    weight: -40
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
